In [2]:
import tensorflow as tf

In [ ]:
#1) how to use constant? --> constant()

In [3]:
a=tf.constant(1)
b=tf.constant(2)
c=tf.add(a,b)

In [4]:
sess=tf.Session()

In [5]:
sess.run(c)

3

In [6]:
#2) how to use variable? --> variable()

In [7]:
a=tf.Variable(5)
b=tf.Variable(3)
c=tf.multiply(a,b)

In [8]:
init=tf.global_variables_initializer()

In [9]:
sess.run(init)

In [11]:
sess.run(c)

15

In [13]:
#3) what is tensor? --> 여러개의 숫자를 한번에 연산할 수 있는 자료형(consider MATRIX) -->리스트 형식을 빌려 숫자 여러개 할당

In [16]:
x=tf.constant([2,4,6])
y=tf.constant([3,6,9])
z=tf.add(x,y)

In [17]:
sess=tf.Session()

In [18]:
sess.run(z)

array([ 5, 10, 15])

In [20]:
MAT1=tf.constant([[5,10,15],#두개의 2X3크기 행렬의 덧셈 연산 구현
                 [20,25,30]])
MAT2=tf.constant([[4,8,12],
                 [16,20,25]])

In [21]:
matResult=tf.add(MAT1,MAT2)

In [22]:
sess=tf.Session()

In [23]:
sess.run(matResult)

array([[ 9, 18, 27],
       [36, 45, 55]])

In [25]:
matShape=MAT1.shape

In [29]:
print(matShape)#shape메서드를 통해 텐서가 몇차원인지 확인 --> "3개의 자료가 들어있는 리스트가 있는데, 해당 리스트가 2개"

(2, 3)


In [30]:
#4) what is placeholder? --> 학습 데이터를 포함하는 변수 --> 일차함수 식에서 x값을 고려(Tensorflow2.x이상부터는 미사용)

In [31]:
input=[1,2,3,4,5]

In [32]:
x=tf.placeholder(dtype=tf.float32)

In [33]:
y=x+5

In [34]:
sess=tf.Session()

In [35]:
sess.run(y, feed_dict={x: input})

array([ 6.,  7.,  8.,  9., 10.], dtype=float32)