In [1]:
#데이터 정규화
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('../data/stock.csv')

In [4]:
#sample과 feature에 대한 정보 확인
df.shape

(99956, 8)

In [5]:
#feature 확인
df.columns

Index(['Order Date', 'Brand', 'Sneaker Name', 'Sale Price', 'Retail Price',
       'Release Date', 'Shoe Size', 'Buyer Region'],
      dtype='object')

In [8]:
#특정 열에 대한 데이터 확인
df['Shoe Size']

0        11.0
1        11.0
2        11.0
3        11.5
4        11.0
         ... 
99951     8.0
99952     8.5
99953     5.5
99954    11.0
99955    11.5
Name: Shoe Size, Length: 99956, dtype: float64

In [22]:
#특정 열의 데이터의 일부분만 확인
size=np.array(df['Shoe Size'])[:100]
size

array([11. , 11. , 11. , 11.5, 11. ,  8.5, 11. , 10. , 11. , 11. , 11.5,
       10. ,  9. , 14. ,  8. , 11. , 11. , 10. ,  9. ,  5.5,  9. ,  9.5,
       14. ,  8. , 11. ,  9. ,  8. , 11.5, 10.5,  8.5, 10. ,  9. ,  9. ,
       14. , 10. ,  9. ,  9. , 11. , 10. , 13. , 10. , 10.5,  9. , 12. ,
        9.5,  9. , 10. ,  9.5, 11. ,  9. , 13. ,  8. ,  5. ,  8.5,  9. ,
       10.5, 10. ,  6.5, 10.5, 10.5,  9.5,  8.5,  9.5, 10.5, 12. ,  9.5,
        8.5, 11. , 14. ,  9.5,  8. ,  6. , 11. ,  5. , 11. , 12. , 11. ,
        9. , 13. ,  9.5,  9.5, 13. , 13. , 11. , 13. , 11. ,  9. ,  9. ,
       10.5, 11.5, 10.5,  9. , 11.5,  7.5,  9. , 10. , 11.5, 11. ,  7.5,
       14. ])

In [18]:
#평균 구하기
mean=np.mean(size)
mean

10.1

In [19]:
#편차 구하기
deviation=size-mean
deviation

array([ 0.9,  0.9,  0.9,  1.4,  0.9, -1.6,  0.9, -0.1,  0.9,  0.9,  1.4,
       -0.1, -1.1,  3.9, -2.1,  0.9,  0.9, -0.1, -1.1, -4.6, -1.1, -0.6,
        3.9, -2.1,  0.9, -1.1, -2.1,  1.4,  0.4, -1.6, -0.1, -1.1, -1.1,
        3.9, -0.1, -1.1, -1.1,  0.9, -0.1,  2.9, -0.1,  0.4, -1.1,  1.9,
       -0.6, -1.1, -0.1, -0.6,  0.9, -1.1,  2.9, -2.1, -5.1, -1.6, -1.1,
        0.4, -0.1, -3.6,  0.4,  0.4, -0.6, -1.6, -0.6,  0.4,  1.9, -0.6,
       -1.6,  0.9,  3.9, -0.6, -2.1, -4.1,  0.9, -5.1,  0.9,  1.9,  0.9,
       -1.1,  2.9, -0.6, -0.6,  2.9,  2.9,  0.9,  2.9,  0.9, -1.1, -1.1,
        0.4,  1.4,  0.4, -1.1,  1.4, -2.6, -1.1, -0.1,  1.4,  0.9, -2.6,
        3.9])

In [20]:
#분산 구하기
np.var(size)

3.4099999999999993

In [23]:
#정규화
z=(size-mean)/np.std(size)
z

array([ 0.48737732,  0.48737732,  0.48737732,  0.75814251,  0.48737732,
       -0.86644858,  0.48737732, -0.05415304,  0.48737732,  0.48737732,
        0.75814251, -0.05415304, -0.5956834 ,  2.11196841, -1.13721376,
        0.48737732,  0.48737732, -0.05415304, -0.5956834 , -2.49103966,
       -0.5956834 , -0.32491822,  2.11196841, -1.13721376,  0.48737732,
       -0.5956834 , -1.13721376,  0.75814251,  0.21661214, -0.86644858,
       -0.05415304, -0.5956834 , -0.5956834 ,  2.11196841, -0.05415304,
       -0.5956834 , -0.5956834 ,  0.48737732, -0.05415304,  1.57043805,
       -0.05415304,  0.21661214, -0.5956834 ,  1.02890769, -0.32491822,
       -0.5956834 , -0.05415304, -0.32491822,  0.48737732, -0.5956834 ,
        1.57043805, -1.13721376, -2.76180484, -0.86644858, -0.5956834 ,
        0.21661214, -0.05415304, -1.9495093 ,  0.21661214,  0.21661214,
       -0.32491822, -0.86644858, -0.32491822,  0.21661214,  1.02890769,
       -0.32491822, -0.86644858,  0.48737732,  2.11196841, -0.32