In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('../data/train.csv')
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
salePrice=np.array(df['SalePrice'])[:10]
salePrice

array([208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000,
       129900, 118000], dtype=int64)

In [5]:
# 산포도 지표
# 1. 편차 --> 데이터가 평균으로부터 얼마나 떨어져있는가를 나타내는 지표
# numpy의 브로드캐스트 기능 --> array 각 원소에 대해 계산
mean=np.mean(salePrice)
deviation=salePrice-mean
deviation

array([ 18360.,  -8640.,  33360., -50140.,  59860., -47140., 116860.,
         9860., -60240., -72140.])

In [6]:
#편차의 대푯값으로 평균 선택
np.mean(deviation)

0.0

In [10]:
# 2. 분산 --> 편차의 음수성을 제거하기 위해 제곱을 취한 뒤 합한 값이 분산
data={'student':['A','B','C','D','E','F','G','H','I','J'],
      'score':[42,69,56,41,57,48,65,49,65,58]}
mat=pd.DataFrame(data)
mat

student  score
0       A     42
1       B     69
2       C     56
3       D     41
4       E     57
5       F     48
6       G     65
7       H     49
8       I     65
9       J     58

In [16]:
values=np.array(mat['score'])[:10]
values

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [17]:
m=np.mean(values)
d=values-m
d

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [18]:
np.mean(d**2)

86.0

In [19]:
#numpy의 var메서드를 사용해 분산 구하기
np.var(values)

86.0

In [20]:
# 3. 표준편차
np.std(values, ddof=0)

9.273618495495704